### ISSUE TITLE
prioritize() should keep rows of score 1 for all sectors?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.match#101]
@jdhoffa can you confirm this is a bug? 

I expected the output to be identical to the input but instead it has one row less -- and I see no reason why the "shipping" `sector_ald` should be prioritized over "automotive".

``` r
library(r2dii.match)

# Minimal data derived from
# loanbook_demo %>% filter(id_loan == "L162")
matched <- tibble::tribble(
  ~id_loan,   ~id,             ~level, ~score,      ~sector,  ~sector_ald,
    "L162", "UP1",  "ultimate_parent",      1, "automotive",   "shipping",
    "L162", "UP1",  "ultimate_parent",      1, "automotive", "automotive",
)

prioritize(matched)
#> # A tibble: 1 x 6
#>   id_loan id    level           score sector     sector_ald
#>   <chr>   <chr> <chr>           <dbl> <chr>      <chr>     
#> 1 L162    UP1   ultimate_parent     1 automotive shipping
```

<sup>Created on 2020-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by jdhoffa** [comment]
Confirmed this is a bug

**Comment by maurolepore** [comment]
I fixed the problem with `sector_ald` (by adding it to the call to `group_ by()` but `sector` seems to have the same problem. I'll fix it too. @jdhoffa:
* Correct me if you think the last result here is not a bug.
* Do you think any other column should also be included in the call to `group_by()`?

``` r
suppressPackageStartupMessages(library(dplyr))
library(r2dii.match)


matched <- tibble::tribble(
  ~id_loan,   ~id,             ~level, ~score,    ~sector,   ~sector_ald,
  "L162", "UP1",  "ultimate_parent",      1, "automotive",  "automotive",
  "L162", "UP1",  "ultimate_parent",      1, "automotive",  "automotive",
)

# Expecting 2 rows, and getting 2 rows. Fixed!
matched %>% 
  mutate(sector_ald = c("shipping", "automotive")) %>% 
  prioritize()
#> # A tibble: 2 x 6
#>   id_loan id    level           score sector     sector_ald
#>   <chr>   <chr> <chr>           <dbl> <chr>      <chr>     
#> 1 L162    UP1   ultimate_parent     1 automotive shipping  
#> 2 L162    UP1   ultimate_parent     1 automotive automotive

# But ...`sector` seems to have the same problem that I fixed in `sector_ald`
# Expecting 2 rows, but getting only 1. 
matched %>% 
  mutate(sector = c("shipping", "automotive")) %>% 
  prioritize()
#> # A tibble: 1 x 6
#>   id_loan id    level           score sector   sector_ald
#>   <chr>   <chr> <chr>           <dbl> <chr>    <chr>     
#> 1 L162    UP1   ultimate_parent     1 shipping automotive
```

<sup>Created on 2020-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I assume this is a bug and will fix it too. @jdhoffa, any other column you think may have a similar problem?

**Comment by jdhoffa** [comment]
Apologies for the late response, but I do think that the latter is in fact a bug, and the fix you wrote makes sense to me

**Comment by maurolepore** [comment]
Thanks!
And I assure there is no other column that we need to group by. (`prioritize()` picks a single row for each group arranged by `level`, with groups currently defined by `id`, `sector`, and `sector_ald`.)
