### ISSUE TITLE
Prioritize does not seem to prioritize (on default priotize_level())

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.match#106]
The output of prioritize() here shows three matches per `id_loan = L155` (one at `ultimate parent` and two at `direct loantaker` with differing `sector`). I have left the `priority` argument with it's default `NULL`. 

``` r
suppressPackageStartupMessages(library(dplyr))
library(r2dii.match)
library(r2dii.dataraw)
#> Loading required package: r2dii.utils

# minimal bugger
loanbook <- r2dii.dataraw::loanbook_demo %>% filter(id_direct_loantaker == "C173")

ald <- r2dii.dataraw::ald_demo

useful_columns <- c("id_loan","id_direct_loantaker", "name_direct_loantaker", "level", 
"name_ald", "sector_ald")

match_name(loanbook,ald) %>% 
  prioritize() %>%
  select(useful_columns)
#> # A tibble: 3 x 6
#>   id_loan id_direct_loanta… name_direct_loantak… level   name_ald     sector_ald
#>   <chr>   <chr>             <chr>                <chr>   <chr>        <chr>     
#> 1 L155    C173              Shanghai Automotive… direct… shanghai au… shipping  
#> 2 L155    C173              Shanghai Automotive… direct… shanghai au… automotive
#> 3 L155    C173              Shanghai Automotive… ultima… guizhou yun… automotive
```

<sup>Created on 2020-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maurolepore** [comment]
@jdhoffa, I'm confused and suspect a conflicting requirement with https://github.com/2DegreesInvesting/r2dii.match/issues/101#issue-549775934.

Can you explain what problem you see and what you expect?

I believe I captured the essence of your example in this smaller reprex. With data like this the output is identical to the input. In this case, which row(s) do you expect the output to have?

``` r
library(r2dii.dataraw)
#> Loading required package: r2dii.utils
library(r2dii.match)

matched <- tibble::tribble(
  ~id_loan,   ~id,             ~level, ~score,      ~sector,  ~sector_ald,
  "L155",   "DL1", "direct_loantaker",      1, "automotive",   "shipping",
  "L155",   "DL1", "direct_loantaker",      1, "automotive", "automotive",
  "L155",   "UP1",  "ultimate_parent",      1, "automotive", "automotive",
)

identical(prioritize(matched), matched)
#> [1] TRUE
```

<sup>Created on 2020-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by jdhoffa** [comment]
Yes, ok you are correct. I think I also misunderstood the purpose of prioritize at the stage of #101 as well, and so my apologies for that rushed response. I know prioritize was developed when I was away, can you remind me Klaus' comment that initiated it's creation? 

In my head, `prioritize` is meant as a fail-safe, to be implemented after the user has manually set each potential match to 1 or 0. The fail-safe portion is meant simply to ensure that each loan gets, at maximum, one ald element merged in. For this reason, I think, now that `prioritize` should truly return, at maximum, 1 row per `id_loan`.

In this sense, I made a mistake in my response to #101, as there should definitely be a prioritization of matches where ´sector = sector.ald´. Beyond this, there will be a case in which no possible prioritization is possible, at which point prioritize should throw an error. 

Let's park this until you wake up, and have a call about it if possible, as I think my confusion on it's purpose may have created a bit of a 1 step forward, 2 steps back situation.

**Comment by maurolepore** [comment]
> can you remind me Klaus' comment that initiated it's creation?

Here you go: https://github.com/2DegreesInvesting/r2dii.match/issues/27

**Comment by jdhoffa** [comment]
Ok, I have spoke to Klaus and aligned on what exactly the purpose is. First, let us assume that there are no sector conflicts (aka `by_sector = TRUE`).

Consider the following case 

``` r
library(r2dii.dataraw)
#> Loading required package: r2dii.utils
library(r2dii.match)

matched <- tibble::tribble(
  ~id_loan,   ~id,             ~level, ~score,      ~sector,  ~sector_ald,
  "L123",   "UP1", "ultimate_parent",      1, "automotive",   "automotive",
  "L456",   "DL1", "direct_loantaker",      1, "automotive", "automotive",
  "L456",   "UP1",  "ultimate_parent",      1, "automotive", "automotive",
)
```

I would expect the output to pick the best match (defined by priority level) per loan (something like this):  

``` r
matched %>% 
  prioritize()
#> # A tibble: 3 x 6
#>   id_loan id_direct_loanta… name_direct_loantak… level   name_ald     sector_ald
#>   <chr>   <chr>             <chr>                <chr>   <chr>        <chr>     
#> 1 L123    C173              Shanghai Automotive… direct… shanghai au… automotive
#> 2 L456    C173              Shanghai Automotive… ultima… guizhou yun… automotive
```

The case of mis-matching sectors is difficult. In this case, it would be up to the user to ensure that, when manually verifying, they did not accidentally match 1 company to two different ald entries in two different sectors.

**Comment by maurolepore** [comment]
> I would expect the output to pick the best match (defined by priority level) per loan

@jdhoffa, I'm confused. 


1. Can you confirm that the default priority is first "direct_loantaker" and last "ultimate_parent"?

This is what the code does right now. But your expectation above suggests I got it the wrong way: where `id_loan` is "L456" you expect `prioritize()` to pick the row where `level` is "ultimate_parent" instead of "direct_loantaker".


``` r
data <- tibble::tibble(
  level = c("intermediate_parent", "ultimate_parent", "direct_loantaker")
)

r2dii.match::prioritize_level(data)
#> [1] "direct_loantaker"    "intermediate_parent" "ultimate_parent"
```

2. Also, where `id_loan` is "L123" you expect `level` to be "direct_loantaker" but the input `matched` does not contain any row where `level` is "direct_loantaker" -- only "ultimate_parent".

Where is the problem? Is there a mistake in your expectation or my mental model of the problem is  broken?

**Comment by maurolepore** [comment]
BTW, https://github.com/2DegreesInvesting/r2dii.match/issues/113 should affect this issue too.

**Comment by jdhoffa** [comment]
Ugh shit that is my mistake

**Comment by jdhoffa** [comment]
The following reprex highlights the bug. I would expect the `level == ultimate_parent` result to be removed by `prioritize()`. Further `id_loan` should not be distinct:

``` r
suppressPackageStartupMessages(library(dplyr))
library(r2dii.dataraw)
#> Loading required package: r2dii.utils
library(r2dii.match)

matched <- match_name(loanbook_demo, ald_demo, by_sector = TRUE)

matched %>% 
  prioritize() %>% 
  filter(id_loan == "L100") %>%
  select(id_loan, id, level, name, name_ald, sector, sector_ald)
#> # A tibble: 2 x 7
#>   id_loan id    level        name             name_ald         sector sector_ald
#>   <chr>   <chr> <chr>        <chr>            <chr>            <chr>  <chr>     
#> 1 L100    DL122 direct_loan… Nagina Cotton M… nagina cotton m… power  power     
#> 2 L100    UP37  ultimate_pa… Bombay Crimper   bombay crimper   power  power
```

<sup>Created on 2020-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maurolepore** [comment]
Thanks, that helps. Just to capture and summarize a discussion on slack:

* Proposed fix:

![](https://i.imgur.com/PCHz6jE.png)

* In https://github.com/2DegreesInvesting/r2dii.match/issues/106#issuecomment-582487743, where it says _"..`.id_loan` should not be distinct"_ it should say _"...`id_loan` should be unique"_
