### ISSUE TITLE
prioritize() should error where input has `score = 1` and duplicated values by `id_loan` and `level`

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.match#114]
Follows a conversation with @jdhoffa

**Comment by maurolepore** [comment]
@jdhoffa, as usual, now that I try to write a test for this issue I realize I understand the problem less well than I thought. I think I'm mislead by my own phrasing in the title of this issue. 

My best bet of what the problem is would better be reflected by this alternative title:

_`prioritize()` with duplicated values by `id_loan` and `level` throws an error._

In code, these are two examples of invalid matched data -- for which we want `prioritize()` to throw an error:

```R
invalid_1 <- tibble::tribble(
  ~id_loan,   ~id,             ~level, ~score,      ~sector,  ~sector_ald,
       "A",   "D", "direct_loantaker",      1, "automotive", "automotive",
       "A",   "D", "direct_loantaker",      1, "automotive", "automotive",
)

invalid_2 <- tibble::tribble(
  ~id_loan,   ~id,             ~level, ~score,      ~sector,  ~sector_ald,
       "A",   "D", "direct_loantaker",      1, "automotive", "automotive",
       "A",   "D", "direct_loantaker",      1, "automotive",       "coal",
)
```

Draft error message (problem statement, error location, hint):

_Matched data can't have duplicated values by `id_loan` and `level`._
_Duplicated rows: 2_
_Have you TODO-GIVE-HINT?_


Can you confirm or clarify my understanding, and maybe fill in TODO-GIVE-HINT?

**Comment by jdhoffa** [comment]
Yes, correct: _prioritize() with duplicated values by id_loan and level throws an error._ is a better description. 
Note however that if the "score" is anything but `1`, prioritize() should still pass without error: 
```R
invalid_1 <- tibble::tribble(
  ~id_loan,   ~id,             ~level, ~score,      ~sector,  ~sector_ald,
       "A",   "D", "direct_loantaker",      0, "automotive", "coal",
       "A",   "D", "direct_loantaker",      1, "automotive", "automotive",
)
```
aka, the above should work fine. 
After `match_name()` the user should manually verify matches, and set them to `0` or `1`. 

Case 1: There is NOTHING wrong if the user decides that a direct_loantaker, intermediate_parent and ultimate_parent all match to different entities in the ald. 

Case 2: However, there IS something wrong if the user decides that, for one particular loan, the direct_loantaker, for example, matches to two different ald entities (this doesnt make sense, and we have no way of knowing how to prioritize this.

Case 2 is what we are trying to test for. 

TODO-GIVE-HINT - "Have you ensured that every name in the loanbook is validated only for one name in the ald?" (or something like this)
