### ISSUE TITLE
overwrite_demo cannot join in manual matches at `direct_loantaker` level

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.match#116]
I've elucidated a bug that may require further thinking. The current `overwrite_demo` file only works at `ultimate_parent` level. This is because internally `match_name` rewrites all `id_*` columns (as expected/ necessary) however id's at `direct_loantaker` level go from: `C` to `DL` and back to `C` while at ultimate parent, they remain as `UP`. 

This actually means that the fact that `overwrite_demo` actually works at `ultimate_parent` level is sort of a fluke (since in principle we could have decided to generate any ID that we wanted). 

``` r
library(r2dii.dataraw)
#> Loading required package: r2dii.utils
library(r2dii.match)
suppressPackageStartupMessages(
  library(dplyr)
)

mini_lbk <- filter(loanbook_demo, name_direct_loantaker == "Yuamen Xinneng Thermal Power Co Ltd") 
mini_lbk %>% select(id_direct_loantaker, name_direct_loantaker)
#> # A tibble: 1 x 2
#>   id_direct_loantaker name_direct_loantaker              
#>   <chr>               <chr>                              
#> 1 C294                Yuamen Xinneng Thermal Power Co Ltd

mini_lbk %>% tibble::rowid_to_column() %>% 
  r2dii.match:::restructure_loanbook_for_matching() %>% 
  filter(name == "Yuamen Xinneng Thermal Power Co Ltd") %>% 
  select(id, name)
#> Uniquifying: id_direct_loantaker, id_intermediate_parent_1, id_ultimate_parent
#> Adding new columns `sector` and `borderline`.
#> # A tibble: 1 x 2
#>   id    name                               
#>   <chr> <chr>                              
#> 1 DL1   Yuamen Xinneng Thermal Power Co Ltd

mini_lbk %>% match_name(ald_demo) %>% 
  select(id_direct_loantaker, name_direct_loantaker)
#> # A tibble: 1 x 2
#>   id_direct_loantaker name_direct_loantaker              
#>   <chr>               <chr>                              
#> 1 C294                Yuamen Xinneng Thermal Power Co Ltd

overwrite_demo %>% filter(id=="C294")
#> # A tibble: 1 x 5
#>   level            id    name                 sector source
#>   <chr>            <chr> <chr>                <chr>  <chr> 
#> 1 direct_loantaker C294  yuamen power company coal   manual
```

<sup>Created on 2020-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

To solve this, we are going to need to decide how the user should interact with the code. I think that, to do manual additions, the user should be forced to use whatever IDs we generate, since we can be certain that these won't be corrupt, however, we will need to find a way to elucidate to the user what these new IDs are. 

To do this, I think that the output of match_name should return not the original ID columns, but the generated sector+name ID columns.

**Comment by maurolepore** [comment]
@jdhoffa, how we handle ids is unclear to me. See https://github.com/2DegreesInvesting/r2dii.match/issues/86#issuecomment-574305698. Can we remove the `overwrite` feature to impair the spread of this bug, and re-add it later -- once I understand how we handle ids?

**Comment by jdhoffa** [comment]
- [ ] Add description of output columns to match_name documentation
- [ ] Change all references from `id` to `id_2dii` to expose that these were generated internally
- [ ] Update `overwrite_demo` file to utilize `id_2dii` ids

**Comment by maurolepore** [comment]
Thanks @jdhoffa for the meeting. To follow this up, I assigned you #123 and #125. And I assigned #124 and #126 to myself.

**Comment by jdhoffa** [comment]
As far as I can tell, this issue can be closed?
