### ISSUE TITLE
Add description of output columns to match_name documentation

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.match#123]

**Comment by maurolepore** [comment]
Closed by #132 

(I thought that "solves" was a valid GitHub keyword but it's [not listed as such](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).)

**Comment by jdhoffa** [comment]
interesting haha
