### ISSUE TITLE
Add warning to ensure user manually validates between `match_name()` and `prioritize()`

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.match#140]
"As far as the "BAD THINGS CAN HAPPEN", I think this makes more sense to include in the description of `prioritize()`, where the validation step should actually be done: "

Add a warning in the description file of `prioritize()` ensuring that the user has manually validated the output of `match_name()`. 

_Originally posted by @jdhoffa in https://github.com/2DegreesInvesting/r2dii.analysis/pull/29#issuecomment-588123844_

**Comment by maurolepore** [comment]
Cool. How about this?

``` r
match_name <- function(..., quietly = FALSE) {
  # do stuff
  if (!quietly) {
    usethis::ui_line("Next:")
    usethis::ui_todo("Validate matches (see how at <bit.ly/tutorial>)")
    usethis::ui_todo("Prioritize validated matches with {usethis::ui_code('prioritize()')}")
  }
}

match_name()
#> Next:
#> ● Validate matches (see how at <bit.ly/tutorial>)
#> ● Prioritize validated matches with `prioritize()`
```

<sup>Created on 2020-02-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maurolepore** [comment]
Nerver mind, I see https://github.com/2DegreesInvesting/r2dii.match/pull/142 only now and it looks great.

**Comment by jdhoffa** [comment]
I actually like the UI command prompt checklist as well
