### ISSUE TITLE
Matching coverage

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.match#141]
We should include a function between `match_name()` and `prioritize()` that calculates matching coverage. 

The workflow would become: 
``` r
loanbook %>%
   match_name() %>%

   ... this section could be repeated until the user is happy
   MANUALLY VALIDATE %>%
   check_coverage %>%
   ADD MANUAL MATCHES (using overwrite file) %>%
   check_coverage %>%
   ...
 
   prioritze()

```

**Comment by maurolepore** [comment]
What is "coverage"? Is it this?:
```
number of rows with score = 1 / total number of rows
```

**Comment by jdhoffa** [comment]
So we would define `coverage` in terms of:
`(exposure with score == 1) / total `
- Note: `exposure` here can mean either `loan_size_outstanding` or `loan_size_credit_limit` (and the user should be able to choose which exposure to show) 
- There should be several coverage metrics (`overall coverage`,`sector-wise coverage`). 
- Could also be useful to return the top 10 unmatched loans (by $) per sector, that were not matched  (to help with manual additions). 
- Could also be useful to return number of direct_loantakers matched vs. number of ultimate_parents
