### ISSUE TITLE
Warn that overwriting sector for an UP affects all its DL (in r2dii.match.Rmd)

### ISSUE THREAD

**Issue by fpalandri** [2DegreesInvesting/r2dii.match#145]
In vignettes/r2dii.match.Rmd, section "Maybe overwrite matches" 

Add a warning to the user that overwriting a UP's sector amounts to overwriting all of its children's sectors, which can - *but in most cases will not* - be what the user means to achieve.

Manual matches & sector 'overwritings' should be done at the DL level wherever possible.

**Comment by jdhoffa** [comment]
Write blurb on `intermediate_parents`

**Comment by maurolepore** [comment]
Thanks! Do kind of warning do you think it's best?:

1. text written in the vignette;
2. a warning message thrown by `match_name()`;
3. both 1. and 2.

**Comment by jdhoffa** [comment]
I would opt for 3. It's kind of a subtle point, so a vignette could be helpful

**Comment by maurolepore** [comment]
Closed by https://github.com/2DegreesInvesting/r2dii.match/pull/163
