### ISSUE TITLE
simplifying with `ifelse`

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/r2dii.match#154]
https://github.com/2DegreesInvesting/r2dii.match/blob/9d3ed2ec726223e9edf09cc4850628038fbf3473/R/match_name.R#L150-L154

if else statements like this can be reduced, and potentially made easier to understand with `ifelse()`, for example...

```
func <- function(choice) {
  if (choice) {
    return("TRUE!")
  } else {
    "FALSE!"
  }
}
```
is equivalent to
```
func <- function(choice) {
  ifelse(choice, "TRUE!", "FALSE!")
}
```

**Comment by maurolepore** [comment]
Thanks @cjyetman. Did you mean to add the label bug? Or was it added automatically?

**Comment by cjyetman** [comment]
When I make a new issue, it only gives me a few options, and “bug” was the most relevant of the choices, though obviously not exactly.

**Comment by maurolepore** [comment]
Thanks, the option "enhancement" was too obscure. It's now more visible: https://github.com/2DegreesInvesting/.github/commit/745274cb072df514bdb594661d230401528cdfe4
