### ISSUE TITLE
Abbreviate country name with ISO Code

### ISSUE THREAD

**Issue by FrederickFa** [2DegreesInvesting/r2dii.match#156]
**Is your feature request related to a problem? Please describe.**
Matching `ikea lithuania` and `ikea slovakia` might return a low score, even though they are likely to match relatively closely. 

For the banks work this is fine, since those companies do not technically match, but if we use this engine for broader purposes, it could be useful to flag the relevance of these matches 

**Describe the solution you'd like**
In `to_alias` convert country names to their iso codes (eg. `lithuania` to `ltu` to decrease it's importance)

**Describe alternatives you've considered**
Leaving the low score, since these companies will evidently not be perfect matches anyway

`r2dii.dataraw::iso_codes` can be used to `grep` from the alias column
```
library(r2dii.dataraw)
iso_codes <- r2dii.dataraw::iso_codes 
```
edited by @jdhoffa

**Comment by maurolepore** [comment]
Nice! Thanks!

@jdhoffa, instead of changing the internals we may show how to replace the company name in their data from "company country" to "company iso"; then the could use the existing tools. Maybe we could build a wrapper around `stringr::str_replace()` in the Get started article. If the tool proves useful we could eventually add it to r2dii.match.

What do you think?

**Comment by jdhoffa** [comment]
I think that's a good idea. I think we should also include this in a "2DII" focused vignette. This functionality is useful for us as analysts, but i dont think banks should be "allowed" to do this, as it could significantly fuck up the matches they get

**Comment by maurolepore** [comment]
Note to myself, this function may help inspire the example to show how to replace countries with their isos:

https://github.com/2DegreesInvesting/r2dii.match/blob/420eaf0f45ef03b7747d9f09099dd24d27f167b8/R/to_alias.R#L115

**Comment by cjyetman** [comment]
As one of the authors of the `countrycode` package, I have way too much experience matching and converting country names and country codes, so I'm happy to advise on this if you need it.

**Comment by maurolepore** [comment]
Amazing! Thanks @cjyetman! I would love your advice on how to get from what we have to what we want (if I understand the problem correctly):

``` r
# we have -----------------------------------------------------------------
company_names <- tibble::tribble(
  ~company_names,
  "ikea lithuania",
  "comp blabla",
)

iso_codes <- tibble::tribble(
  ~country,    ~country_iso,
  "lithuania", "ltu",
  "blabla",    "bla",
)


# we want -----------------------------------------------------------------
company_names2 <- tibble::tribble(
  ~company_names,
  "ikea ltu",
  "comp bla",
)
company_names2
#> # A tibble: 2 x 1
#>   company_names
#>   <chr>        
#> 1 ikea ltu     
#> 2 comp bla
```

<sup>Created on 2020-03-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maurolepore** [comment]
We plan to reconsider after the first release (see https://github.com/2DegreesInvesting/r2dii.match/issues/157#issuecomment-593500310)

**Comment by cjyetman** [comment]
```r
country_to_iso3c <-
  function(x) {
    if (!is.character(x)) { stop('input must be a character vector') }
    
    x_factor <- factor(x)
    x_levels <- levels(x_factor)
    
    x_levels <- 
      sapply(x_levels, function(x_level) {
        for (i in 1:nrow(iso_codes)) { 
          x_level <- gsub(iso_codes$country[[i]], iso_codes$country_iso[[i]], x_level, ignore.case = TRUE)
        }
        x_level
      }, USE.NAMES = FALSE)
    
    levels(x_factor) <- x_levels
    return(as.character(x_factor))
  }


company_names %>% mutate(iso3c = country_to_iso3c(company_names))

# # A tibble: 2 x 2
#   company_names  iso3c   
#   <chr>          <chr>   
# 1 ikea lithuania ikea ltu
# 2 comp blabla    comp bla
```

**Comment by maurolepore** [comment]
Awesome @cjyetman!

@FrederickFa, does this solve your issue?

**Comment by jdhoffa** [comment]
I will close this for now, as I don't think we are planning on adding this into the code immediately.
