### ISSUE TITLE
Announce r2dii.match 0.0.1?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.match#175]
We could use the News tab of r2dii as a blog, similar to the blog tab of the tidyverse (https://www.tidyverse.org/blog/). Like the tidyverse, we could announce Release notes (e.g. https://www.tidyverse.org/blog/2020/03/pkgdown-1-5-0/) and other announcements (e.g. https://www.tidyverse.org/blog/2020/03/dplyr-1-0-0-is-coming-soon/). (An alternative is to create an actual blog but seems like an overkill right now).

An announcement for the release of r2dii.match 0.0.1 would look like this: https://2degreesinvesting.github.io/r2dii/

@jdhoffa and @2diiKlaus, what do you think? 
Should we also (or instead) notify someone in charge of https://2degrees-investing.org/?

**Comment by jdhoffa** [comment]
I like this idea! Let's discuss during our call today

**Comment by maurolepore** [comment]
See https://github.com/2DegreesInvesting/ds-incubator/issues/32
