### ISSUE TITLE
match_name(): Use minimum data yet facilitate context-columns

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.match#236]
@jdhoffa, should we enforce `id_loan` inside `match_name()`? `match_name doesn't use it but it's required later by `prioritize()`. By then, it's too late and the computation can be expensive to redo.

``` r
library(r2dii.data)
library(r2dii.match)
#> Warning: package 'r2dii.match' was built under R version 4.0.2
packageVersion("r2dii.match")
#> [1] '0.0.3'

lbk_cols <- c(
  "id_ultimate_parent",
  "name_ultimate_parent",
  "id_direct_loantaker",
  "name_direct_loantaker",
  "sector_classification_system",
  "sector_classification_direct_loantaker"
)

ald_cols <- c("name_company", "sector")

# This works but ...
lbk <- loanbook_demo[lbk_cols]
ald <- ald_demo[ald_cols]
out <- match_name(lbk, ald)

# Prioritize needs `id_loan`, and it's too late to get it. 
# Should we enforce it from inside `match_name`?
try(prioritize(out))
#> Error : Must have missing names:
#> `id_loan`

# If we keep id_cols, then prioritize() works
lbk2 <- loanbook_demo[c(lbk_cols, "id_loan")]
ald2 <- ald_demo[ald_cols]
out2 <- match_name(lbk2, ald2)
prioritize(out2)
#> # A tibble: 267 x 15
#>    id_ultimate_par… name_ultimate_p… id_direct_loant… name_direct_loa…
#>    <chr>            <chr>            <chr>            <chr>           
#>  1 UP318            Zoox             C168             Shaanxi Auto    
#>  2 UP242            Shandong Kama    C169             Shandong Auto   
#>  3 UP128            Huanghai Motors  C170             Shandong Kama   
#>  4 UP89             Electric Mobili… C171             Shandong Tangju…
#>  5 UP114            Guizhou Yunque   C173             Shanghai Automo…
#>  6 UP145            Jiangling Jingma C176             Shanxi Dayun    
#>  7 UP309            Yulon            C178             Shenyang Polars…
#>  8 UP234            Santana          C180             Shuanghuan Auto 
#>  9 UP202            Otokar           C182             Sichuan Auto    
#> 10 UP185            Morattab         C184             Singulato       
#> # … with 257 more rows, and 11 more variables:
#> #   sector_classification_system <chr>,
#> #   sector_classification_direct_loantaker <dbl>, id_loan <chr>, id_2dii <chr>,
#> #   level <chr>, sector <chr>, sector_ald <chr>, name <chr>, name_ald <chr>,
#> #   score <dbl>, source <chr>
```

<sup>Created on 2020-07-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maurolepore** [comment]
Something similar happens with `loan_size_outstanding`, which isn't necessary for `match_name()` or `prioritize()` but then is required for `target_market_share()`. My takeaway is that we need to make it easier for the user to know what they need for what, so they can feed just what they need -- so that they use as little time and memory as possible.

Enforcing in r2dii.match columns that the user might need in r2dii.analysis seems like a bad idea. Instead I would prefer for each function to take and output as little as possible, and provide a way to join back columns as required for downstream analyses. We may need to enforce just an id column, and maybe write documentation or a helper for the user to checks if a dataset meets the requirements for a given analysis.

(but , recommend, or document

**Comment by jdhoffa** [comment]
I tend to agree, however there is a bit of an issue with this. The columns that are crucial to `match_name()` may not be all the columns that are _useful_ to `match_name()`. 

For example, when an analyst is manually validating, it can be very useful to have values like `loan_size_*` to help prioritize which matches to focus on, but these columns are never explicitly used by `match_name`. 

I would be happy to brainstorm with you, and decide which columns are crucial, and which we believe are useful, and maybe we can just `warn` the user if the _useful_ columns aren't present? What do you think?

**Comment by maurolepore** [comment]
If we enforce a unique `rowid` in the input and we carry it all the way to the output, we might be able to exclude all but the crucial columns, then let the user join back the columns they need for context. That way we get the best of both worlds: `match_name()` uses as little time and memory as possible, and the user can add the context they need.

**Comment by jdhoffa** [comment]
I like this idea.

**Comment by maurolepore** [comment]
I'll close this now. Right now I think it's best for users to be the ones who add the rowid.
