### ISSUE TITLE
`match_name()` should output the column `borderline`

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.match#258]
`r2dii.data` has a series of sector code classification datafiles, each of which has a column `borderline`. This flag is `FALSE` if the sector classification code perfectly aligns with a 2dii sector, and `TRUE` if the sector may include one, but might not. 

This would be a good column to output, as it can be used to determine the coverage of the matching easily. 

This PR should inlude an article explaining `borderline`

**Comment by maurolepore** [comment]
Should we include this in the upcoming release?

**Comment by jdhoffa** [comment]
I think it wouldn't hurt.

**Comment by jdhoffa** [comment]
It should be as simple as adding it to a call to `select()`. If it seems like it will take longer than ~10min, then I would say forget about it, and proceed with the release

**Comment by maurolepore** [comment]
I agree, the change should be quick and safe. What might take longer is the article. If you want it in the same PR, I’d appreciate your help. Else, we can show the feature in the blog post that announces the release.

**Comment by jdhoffa** [comment]
Absolutely, I can help today if you'd like to work on it together
