### ISSUE TITLE
Define priority of company level in matching

### ISSUE THREAD

**Issue by 2diiKlaus** [2DegreesInvesting/r2dii.match#27]
**Is your feature request related to a problem? Please describe.**
The issue of banks providing different amount and names for loan-takers.

**Describe the solution you'd like**
We will define clear input rules with unlimited levels for the loanbook and preset the priority:
direct_loantaker
intermediate_company_1
intermediate_company_2
...
intermediate_company_n
ultimate_parent

For each level, the name needs to be given. An ID for tracking of matches will be generated and stored. The sector is taken from the direct_loantaker in all cases

**Describe alternatives you've considered**
Adding the priority in the parameter file -> to error-prone
Letting banks interactively define the priorities -> need basic R skill of user which sometimes is a problem

**Additional context**
See discussion between Jackson and Klaus on the 26th of November at ~11.30 am at slack

**Can you provide something like this?**
No

Needs to be reflected in the loan book object
Need a function to count levels provided
Mapping function needs to use pre-defined prioritization.

**Comment by maurolepore** [comment]
https://github.com/forestgeo/fgeo.biomass/blob/bb292e2e772ed6b64bf27cf4f94e5644079491df/R/bind_winner_loser.R

https://github.com/forestgeo/fgeo.biomass/blob/bb292e2e772ed6b64bf27cf4f94e5644079491df/R/rowbind_inorder.R

[rowbind_inorder.R.txt](https://github.com/2DegreesInvesting/r2dii.match/files/4010961/rowbind_inorder.R.txt)
[bind_winner_loser.R.txt](https://github.com/2DegreesInvesting/r2dii.match/files/4010962/bind_winner_loser.R.txt)

**Comment by maurolepore** [comment]
@2diiKlaus and @jdhoffa, #58 implemented `prioritize_at()` to allow users to set a level-priority and pick only one of the potentially multiple matches. See this in action [here](https://2degreesinvesting.github.io/r2dii.match/index.html#pick-validated-mathes-score-1-and-prioritize-by-level) and please let me know if this or something else is what you want.

The example shows a hard-coded priority based on your comment at the top:

> We will define clear input rules with unlimited levels for the loanbook and preset the priority:

```
direct_loantaker
intermediate_company_1
intermediate_company_2
...
intermediate_company_n
ultimate_parent
```

But maybe we need some helper to set the priority based on some heuristic?

**Comment by maurolepore** [comment]
RE the helper to set priority: see https://github.com/2DegreesInvesting/r2dii.match/pull/64#issuecomment-570439607

**Comment by 2diiKlaus** [comment]
@maurolepore: Think it looks good in action, only 3 things I came across / would like to clarify:
1) I saw the following question in "ASK TODO: Can we provide a default priority?"
I guess your helper #64 does exactly this or in other words the following is the default:
> direct_loantaker
intermediate_company_1
intermediate_company_2
...
intermediate_company_n
ultimate_parent

2) The other potential prioritization is exactly the other way round, i.e. ultimate_parent, intermediate_company_n, .... intermediate_company_1, direct_loantaker. This can be used for a completely different research question. 
@maurolepore How could I as a user set a different priority - especially considering that most users would not go into the details but rather use just the wrapper-function for the matching step?

3) Just to make sure as I think the functions works in that way already: Per loan the function takes the best match correct? What I mean by that is that the same company could have the best match for loan1 at `intermediate_company_1` level and loan2 at `direct_loantaker ` level (basically if the loans are given to different levels in the company tree and we do not have all subsidiaries in our data). The code would use the best match per loan in this case, i.e. `loan1` at `intermediate_company_1` level and `loan2` at `direct_loantaker ` level correct?

**Comment by maurolepore** [comment]
@2diiKlaus,

RE 1.: Thanks for your confirmation. Then I'll make this the default.

RE 2.: The default priority can be reversed with `rev()`. The wrapper could have a `reverse_priority` argument, but I think it's not worthwhile the trouble of making the interface of the wrapper more complex. Instead I could show in an example how to use `rev()` with the default priority we provide.

``` r
default_priority <- c(
  "direct_loantaker",
  "intermediate_company_1",
  "intermediate_company_2",
  "intermediate_company_n",
  "ultimate_parent"
)

rev(default_priority)
#> [1] "ultimate_parent"        "intermediate_company_n" "intermediate_company_2"
#> [4] "intermediate_company_1" "direct_loantaker"
```

RE 3.: 

> Per loan the function takes the best match correct?

If I'm understanding correctly, we can certainly do that, if we first `group_by("id_lbk")` before we `prioritize_at("level_lbk")`.

``` r
library(tidyverse)
library(r2dii.match)

matched <- tribble(
                   ~name_lbk,           ~name_ald, ~id_lbk,              ~level_lbk,         ~alias_lbk,         ~alias_ald, ~score,
                          NA,        "tata group",    "C1",       "ultimate_parent",          "tatagrp",          "tatagrp",      1,
                          NA, "toyota motor corp",    "C3", "intermediate_parent_1", "toyotamotor corp", "toyotamotor corp",      1,
                          NA, "toyota motor corp",    "C3", "intermediate_parent_1", "toyotamotor corp", "toyotamotor corp",      1,
                          NA,        "tata group",    "C2", "intermediate_parent_1",          "tatagrp",          "tatagrp",      1,
  "Toyota Motor Corporation", "toyota motor corp",    "C3",      "direct_loantaker", "toyotamotor corp", "toyotamotor corp",      1,
                          NA, "toyota motor corp",    "C3",       "ultimate_parent", "toyotamotor corp", "toyotamotor corp",      1,
                          NA, "toyota motor corp",   "UP3", "intermediate_parent_1", "toyotamotor corp", "toyotamotor corp",      1,
                          NA,   "saic gm dongyue",   "UP1",      "direct_loantaker",    "saicgmdongyue",    "saicgmdongyue",      1,
                          NA,        "tata group",    "C2",       "ultimate_parent",          "tatagrp",          "tatagrp",      1,
         "Toyota Motor Corp", "toyota motor corp",   "UP3",       "ultimate_parent", "toyotamotor corp", "toyotamotor corp",      1
  )

matched
#> # A tibble: 10 x 7
#>    name_lbk       name_ald    id_lbk level_lbk     alias_lbk   alias_ald   score
#>    <chr>          <chr>       <chr>  <chr>         <chr>       <chr>       <dbl>
#>  1 <NA>           tata group  C1     ultimate_par… tatagrp     tatagrp         1
#>  2 <NA>           toyota mot… C3     intermediate… toyotamoto… toyotamoto…     1
#>  3 <NA>           toyota mot… C3     intermediate… toyotamoto… toyotamoto…     1
#>  4 <NA>           tata group  C2     intermediate… tatagrp     tatagrp         1
#>  5 Toyota Motor … toyota mot… C3     direct_loant… toyotamoto… toyotamoto…     1
#>  6 <NA>           toyota mot… C3     ultimate_par… toyotamoto… toyotamoto…     1
#>  7 <NA>           toyota mot… UP3    intermediate… toyotamoto… toyotamoto…     1
#>  8 <NA>           saic gm do… UP1    direct_loant… saicgmdong… saicgmdong…     1
#>  9 <NA>           tata group  C2     ultimate_par… tatagrp     tatagrp         1
#> 10 Toyota Motor … toyota mot… UP3    ultimate_par… toyotamoto… toyotamoto…     1

# Good
matched %>% 
  group_by(id_lbk) %>% 
  prioritize_at("level_lbk")
#> # A tibble: 5 x 7
#> # Groups:   id_lbk [5]
#>   name_lbk       name_ald     id_lbk level_lbk     alias_lbk   alias_ald   score
#>   <chr>          <chr>        <chr>  <chr>         <chr>       <chr>       <dbl>
#> 1 Toyota Motor … toyota moto… C3     direct_loant… toyotamoto… toyotamoto…     1
#> 2 <NA>           saic gm don… UP1    direct_loant… saicgmdong… saicgmdong…     1
#> 3 <NA>           tata group   C2     intermediate… tatagrp     tatagrp         1
#> 4 <NA>           toyota moto… UP3    intermediate… toyotamoto… toyotamoto…     1
#> 5 <NA>           tata group   C1     ultimate_par… tatagrp     tatagrp         1

# Bad
matched %>% 
  prioritize_at("level_lbk")
#> # A tibble: 1 x 7
#>   name_lbk        name_ald     id_lbk level_lbk    alias_lbk   alias_ald   score
#>   <chr>           <chr>        <chr>  <chr>        <chr>       <chr>       <dbl>
#> 1 Toyota Motor C… toyota moto… C3     direct_loan… toyotamoto… toyotamoto…     1
```

@2diiKlaus, please confirm:

3.a. Are these the correct columns?

```
... %>%
  group_by(id_lbk) %>% 
  prioritize_at("level_lbk")
```

3.b. Is this a permanent-enough grouping that should "just happen" within the wrapper? (as opposed to leaving it up to the user to call `group_by()` in case they want to group by something other than `id_lbk`)

**Comment by maurolepore** [comment]
@2diiKlaus and @jdhoffa, 

Here is my attempt to address this issue.

``` r
library(r2dii.match)
suppressPackageStartupMessages(
  library(dplyr)
)

# A minimal portion of validated data (i.e. the output of `match_name()` + user edits)
matched <- tribble(
  ~score, ~id_lbk, ~level_lbk,
  1,      "aa",    "ultimate_parent",
  1,      "aa",    "direct_loantaker",
  1,      "bb",    "intermediate_parent",
  1,      "bb",    "ultimate_parent",
)

# The priority we use by default
prioritize_level(matched)
#> [1] "direct_loantaker"    "intermediate_parent" "ultimate_parent"

# Using default priority
prioritize(matched)
#> # A tibble: 2 x 3
#>   score id_lbk level_lbk          
#>   <dbl> <chr>  <chr>              
#> 1     1 aa     direct_loantaker   
#> 2     1 bb     intermediate_parent

# Using the reverse of the default priority
prioritize(matched, priority = rev)
#> # A tibble: 2 x 3
#>   score id_lbk level_lbk      
#>   <dbl> <chr>  <chr>          
#> 1     1 aa     ultimate_parent
#> 2     1 bb     ultimate_parent

# Same
prioritize(matched, priority = ~ rev(.x))
#> # A tibble: 2 x 3
#>   score id_lbk level_lbk      
#>   <dbl> <chr>  <chr>          
#> 1     1 aa     ultimate_parent
#> 2     1 bb     ultimate_parent

# Using a custom priority
bad_idea <- select_chr(
  matched$level_lbk,
  matches("intermediate"),
  everything()
)
bad_idea
#> [1] "intermediate_parent" "ultimate_parent"     "direct_loantaker"

prioritize(matched, priority = bad_idea)
#> # A tibble: 2 x 3
#>   score id_lbk level_lbk          
#>   <dbl> <chr>  <chr>              
#> 1     1 bb     intermediate_parent
#> 2     1 aa     ultimate_parent
```

<sup>Created on 2020-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>


I'll close this issue but feel free to reopen if needed.

**Comment by 2diiKlaus** [comment]
@jdhoffa is id_lbk the loan level id? because it looks like it is the company level id to me. I guess it is actually the id at loan level and if you can confirm this, i hereby confirm that what @maurolepore did is exactly what we need

**Comment by jdhoffa** [comment]
it is (or at least should be) the id at loan level
