### ISSUE TITLE
update sector_classifications in `r2dii.data` cause regression tests to fail

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.match#311]
In 2DegreesInvesting/r2dii.data#170, I fixed several sector classification bridges. This has caused some of the regression tests in `r2dii.match` to fail, as the output depends on if the entity is within a sector or not. 

I will update the regression values for now.

**Comment by maurolepore** [comment]
@jdhoffa is this closed via your #312 ?

**Comment by maurolepore** [comment]
We seem to have fixed this.
