### ISSUE TITLE
Depend less on `r2dii.data`, maybe via `*_stable` datasets

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.match#325]
Insofar as it is doable, we should aim to reduce the dependency on `r2dii.data` output as much as possible in the tests in this package.

https://github.com/2DegreesInvesting/r2dii.match/pull/323#pullrequestreview-536401088

**Comment by jdhoffa** [comment]
After looking a bit deeper, I think the current solution is our easiest option, without doing some decently serious work (and it seems we have other priorities).

**Comment by maurolepore** [comment]
It'd be good to capture here your learning from that deep exploration -- at least at a high level.

**Comment by jdhoffa** [comment]
Hopefully this gives some context. The columns `sector` and `borderline` of the output of `match_name()` are pulled directly from `r2dii.data` internally (see below). 

I would prefer not to extract this object as an argument, even with a default value, as I think this adds some unnecessary complication to a function that our users are already sometimes confused by (the `region_isos` argument has been a topic for a lot of confusion). 

If we cannot extract this object as an argument, then we basically can't ensure that the output will have consistent `sector` and `borderline` output. 

One, somewhat clunky, option would be to add a `demo_classification` dataframe that we are sure will be stable, however I'm not a huge fan of this from a maintenance perspective. 

Another option, which I'm leaning more towards, is to simply ignore the `sector` and `borderline` output in our tests, and expect that these are sufficiently tested in `r2dii.data`, although there are obviously downsides to this approach as well. 

Let me know what your thoughts are.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(r2dii.data)
library(r2dii.match)

lbk <- tibble::tribble(
  ~sector_classification_system, ~id_ultimate_parent,             ~name_ultimate_parent, ~id_direct_loantaker,                ~name_direct_loantaker, ~sector_classification_direct_loantaker,
  "NACE",              "UP15", "Alpine Knits India Pvt. Limited",               "C294", "Yuamen Xinneng Thermal Power Co Ltd",                                    3511
)

ald <- tibble::tribble(
  ~name_company, ~sector,                ~alias_ald,
  "alpine knits india pvt. limited", "power", "alpineknitsindiapvt ltd"
)

# the code given is NACE code 3511
lbk %>% 
  select(sector_classification_system, sector_classification_direct_loantaker)
#> # A tibble: 1 x 2
#>   sector_classification_system sector_classification_direct_loantaker
#>   <chr>                                                         <dbl>
#> 1 NACE                                                           3511

match_name(lbk,ald) %>% 
  select(sector, borderline)
#> # A tibble: 1 x 2
#>   sector borderline
#>   <chr>  <lgl>     
#> 1 power  FALSE

r2dii.data::nace_classification %>% 
  filter(code == 3511) %>% 
  select(sector, borderline)
#> # A tibble: 1 x 2
#>   sector borderline
#>   <chr>  <lgl>     
#> 1 power  FALSE
```

<sup>Created on 2020-11-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maurolepore** [comment]
Closing in favor of #334
