### ISSUE TITLE
`match_name` should allow `loanbook_demo` to have reserved columns `sector` and `borderline` 

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.match#326]
For the purpose of testing, we hope to use a stable `loanbook_demo` with the `sector` and `borderline` predefined, so that it does not depend on changes made in `r2dii.data` (especially to the classification files). 

To do so, `match_name` must allow for `sector` and `borderline` to exist in the `loanbook_demo` input. 

Relates to 2DegreesInvesting/r2dii.analysis#227

**Comment by maurolepore** [comment]
The reprex below suggests `may_add_sector_and_borderline()` never meets the condition of the first `if()` statement:

```r
# restructure_ald.R L75

may_add_sector_and_borderline <- function(data) {
  if (has_sector_and_borderline(data)) {
    data2 <- data
  } else {
    data2 <- add_sector_and_borderline(data)
  }

  data2
}

```

``` r
lbk <- dplyr::mutate(r2dii.data::loanbook_demo, sector = "a")
ald <- r2dii.data::ald_demo
r2dii.match::match_name(lbk, ald)
#> Error: `loanbook` can't have reserved columns:
#> sector
```

<sup>Created on 2020-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
