### ISSUE TITLE
Polish website's Reference tab

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.match#33]
Soon we'll get some beta-users try this code (@2diiKlaus will have a look next week). In preparation for I think the Reference section of the package website should be more informative. Users with little domain knowledge should be able to guess what each function does from their name and title. For inspiration see https://usethis.r-lib.org/reference/index.html.

Here is what we have right now:

https://2degreesinvesting.github.io/r2dii.match/reference/index.html

![image](https://user-images.githubusercontent.com/5856545/70376065-afcb0600-18ca-11ea-8e1a-f1c3554f096c.png)

--

* `id_by_loantaker_sector()`:
     * Does it add a new column `id_*`? 
     * Does it modify an existing column? Which one?
* `match_all_against_all()`: From this name it's difficult to guess that what his function does is to "
Score similarity between simpler_name values in two dataframes".
* `bridge_sector()`: The word "bridge" seems meaningful only for people with domain knowledge. A more general term might be "lookup".

We should also group similar functions together. This is easily done by adding `#' @family <family name>` to each function's helpfile. 

Finally, I'm not convinced that we should export functions that most users will never use. We can always leave internal functions internal, and call them in development mode or with the `:::` notation (as opposed to `::`).

@jdhoffa, You'll probably see a PR with my suggestions.

**Comment by 2diiKlaus** [comment]
**Home**
I think it should be made clearer that the loanbook sample is a template that the banks **have to** use.
Thus the first step for them is preparing the data in this format. I guess it is worth to add a csv-download or something similar for the banks

> "Before matching, both the loanbook and asset level data must be prepared."
here we need to explain what that means? something along the lines of:
"Simplifying the names using best practices used in name matching algorithms such as removing special characters & replacing language specific characters, abbreviating certain names to reduce their importance in the matching, spell numbers to increase their importance.
This creates simpler_name"

> „`match_all_against_all() ` scores the similarity between simpler_name values in the prepared loanbook and ald datasets.“

 Maybe better to call this function match_2_datasets_via_simpler_name (the function is also not limited to ALD <-> loanbook)

I also think that from `match_all_against_all ` the explanation in "home" becomes too specific/detailed. 

In my view, the Home part of the documentation should explain 
a) the goal of the library, which is done well 
b) the inputs for the banks, which needs to become more precise and 
c) a 3 step progress they have to perform. 
Afterwards, we can show all those details to allow capable R-users to dive-into the details and understand to the full extent what we do, adjust it, what so ever. However, main goal: Easy to use
Thus we need a wrapper function for the steps up to validation and one for afterwards (I guess this was planned anyways, just highlighting that from my view the documentation will need to start with those). 

The first wrapper-function should have the inputs: loanbook data, ald, grouping variable (sector, potentially others), confidence threshold (default should be higher 0.5 will create very very weird matches)
The second wrapper-function should have the same inputs plus the validation input.

We could also consider moving all the other details just to the reference part of the library – but I guess for completeness they should appear in the Home tab as well?! 

One specific thing: 
For the manual verification output (csv) we need to add the original names back in and potentially all other relevant information that makes it much easier and user-friendly than just showing the simpler names. 


**Reference**

`match_all_against_all() `
One enhancement I see we can & should do: Would be good to write the function in a way that allows “grouping” by another variable such as country_of_domicile – next version.

`prepare_ald_for_matching() `
The column-names in ALD and loanbook should differ. And the ald needs to align with all other work we are doing. I suggest having ald_ or loanbook_ as a prefix. It helps understanding where datapoints come from.

`bridge_sector()`
I think here we need to be more precise as this is a crucial element. 
“This function bridges (maybe you know a better word) from standard sector classifications to the climate-relevant sectors in the production databases. 

Companies are identified as climate-relevant sector actors 
a)	If they are classified in one of the sectors that translate 1 to 1 from a standard sector classification to a climate-relevant sector covered by the PACTA analysis (e.g. utilities to power)
b)	If they are classified in a sector that can but does not necessarily map to a climate-relevant sector covered by the PACTA analysis (e.g. power grid/network to Power, general mining to coal mining _Can you get better examples here, those are just from the top of my head_)

The current functions allows for using a set of sector classification systems, which are listed below:
NAICS
NACE
ISIC _please update this list_”

`id_by_loantaker_sector()`
`replace_customer_name() get_replacements() `
`string_similarity()`
Maybe not easy to understand what those do, but I think that is fine for now

**Comment by maurolepore** [comment]
@2diiKlaus and @jdhoffa, I've polished the function names and titles, and classified them as either user-facing or internal-ish. 

I think this is ready for another pass of your feedback. Let me know your suggestions to make this more precise and clearer.

https://2degreesinvesting.github.io/r2dii.match/reference/index.html

**Comment by maurolepore** [comment]
I'll call it done for now but feel free to reopen if needed.

**Comment by 2diiKlaus** [comment]
@jdhoffa : For making it fully dummy approved we need to have a workscript in the bank meta-package that does run both steps + the merging and then the analysis steps.
I am just mentioning this as the merging (loanbook to ALD) is not being done in this package as far as I see and as we discussed the analysis package will start with the merged loanbook (or potentially start with the loanbook, the bridge and the ALD). 
Any option is fine with me, however this "gap" needs to be bridged somewhere.
I know I am pointing out the obvious ;)

**Comment by jdhoffa** [comment]
Yup understood. Personally, I'd rather bridge the gap as an input function in the analysis library (at least let's start that way) and if it makes more sense to have it here we can move it later
