### ISSUE TITLE
Add company ID to ald_demo

### ISSUE THREAD

**Issue by vintented** [2DegreesInvesting/r2dii.match#355]
It would be great to add company IDs (unique numeric sequence) to ald_demo so Asset Resolution can start integrating them into the PACTA for Bank datasets. This addition would ensure that production is always aggregated to the correct entity and help with QA issues and tracking. 

Let me know if I can provide any additional details.

**Comment by jdhoffa** [comment]
I moved this issue to `r2dii.match`, as the remainder of the fix will be in actually allowing the user to implement the `id_company` in the matching process.
