### ISSUE TITLE
Do we need to describe `borderline`?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.match#38]
@jdhoffa,

The column `borderline` appears in the output of `?r2dii.match::bridge_sector()` and in the `?r2dii.dataraw::classification_bridge` datasets. But AFAIK it's documented nowhere. Do we need to describe it?

**Comment by 2diiKlaus** [comment]
Here my general comment about `?r2dii.match::bridge_sector()`
I think here we need to be more precise as this is a crucial element. 
“This function bridges _(maybe you know a better word)_ from standard sector classifications to the climate-relevant sectors in the production databases. 

Companies are identified as climate-relevant sector actors 
a)  If they are classified in one of the sectors that translate 1 to 1 from a standard sector classification to a climate relevant sector covered by the PACTA analysis (e.g. utilities to power)
b)  If they are classified in a sector that can but does not necessarily map to a climate-relevant sector covered by the PACTA analysis (e.g. power grid/network to Power, general mining to coal mining _we should get better examples here!)_

The current functions allows for using a set of sector classification systems, which are listed below:
NAICS
NACE
ISIC _please update this list_”

**Comment by maurolepore** [comment]
The above feedback has been incorporated in the help file of `bridge_sector()`.
I'm now inclined to be less picky about `borderline` because -- since `match_name()` became the top-level wrapper -- I see `bridge_sector()` as an internal-ish function.
