### ISSUE TITLE
prefer perfect matches

### ISSUE THREAD

**Issue by 2diiKlaus** [2DegreesInvesting/r2dii.match#40]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/>, <https://community.rstudio.com/> or email Mauro Lepore at <mauro@2degrees-investing.org>.

Too many possible matches are shown in the current version. There are 2 easy solutions:
a) In case there is a perfect match, all others should not be kept - no matter of the threshold
b) The threshold should already be introduced here

---

Brief description of the problem

# 
``` r
tibble::tribble(
  ~simpler_name_x, ~simpler_name_y,            ~score,
    "astonmartin",   "astonmartin",                 1,
    "astonmartin",       "avtozaz", 0.680519480519481,
    "astonmartin",        "bogdan",  0.47979797979798,
    "astonmartin",        "chauto", 0.590909090909091,
    "astonmartin",      "chehejia", 0.310606060606061,
    "astonmartin",      "chtcauto", 0.454545454545455
  )
#> # A tibble: 6 x 3
#>   simpler_name_x simpler_name_y score
#>   <chr>          <chr>          <dbl>
#> 1 astonmartin    astonmartin    1    
#> 2 astonmartin    avtozaz        0.681
#> 3 astonmartin    bogdan         0.480
#> 4 astonmartin    chauto         0.591
#> 5 astonmartin    chehejia       0.311
#> 6 astonmartin    chtcauto       0.455
```

<sup>Created on 2019-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maurolepore** [comment]
@2diiKlaus, 

This example is to check whether or not I interpret this issue correctly, and to expose a potential grey area or bug.

Here are some cases for you to confirm or specify the behaviour you want:

(1) When for a given `simpler_name_lbk` we have one row with `score` of 1 and other rows with `score` < 1, We keep the one row with `score` of 1? In the example below, we keep row 2 and we drop row 3.

(2) If for a given `simpler_name` we get more than one row with `score` of  1, Do we keep all rows with `score` of 1? The example below does not show this case.

I think the next case will not be an option one we implement  https://github.com/2DegreesInvesting/r2dii.match/issues/27#issuecomment-561173274, but just in case here it goes:

(3) If for a given `name_direct_loantaker` (e.g. "Nanaimo Forest Products Ltd.") we get more than one row with `score` of 1, Do we keep all rows with `score` of 1, even if some of those rows come from a perfect match not in `name_direct_loantaker` but from a perfect match in `name_ultimate_parent`?`^[1]` In the example below, we keep rows 1 and 2, and we drop row 3.



``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(r2dii.dataraw)
#> Loading required package: r2dii.utils
library(r2dii.match)

nanaimo_lbk <- loanbook_demo %>% 
  filter(name_direct_loantaker == "Nanaimo Forest Products Ltd.")

match_name(nanaimo_lbk, ald_demo) %>% 
  select(
    score, 
    starts_with("simpler_"), 
    name_direct_loantaker_lbk,
    name_ultimate_parent_lbk
  )
#> # A tibble: 3 x 5
#>   score simpler_name_lbk  simpler_name_ald   name_direct_loan… name_ultimate_pa…
#>   <dbl> <chr>             <chr>              <chr>             <chr>            
#> 1 1     abahydropowergen… abahydropowergenc… <NA>              Aba Hydropower G…
#> 2 1     nanaimoforestpro… nanaimoforestprod… Nanaimo Forest P… <NA>             
#> 3 0.811 nanaimoforestpro… nandirollerflourm… Nanaimo Forest P… <NA>
```

<sup>Created on 2019-12-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by maurolepore** [comment]
`match_name()` now prefers perfect matches by `simpler_name_lbk`. The same reprex I run above now excludes the row where `sector` is not `1`.

I am still unsure if `simpler_name_lbk` is the only variable to group by. I may be clearer on this once I work on #27. 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(r2dii.dataraw)
#> Loading required package: r2dii.utils
library(r2dii.match)

nanaimo_lbk <- loanbook_demo %>% 
  filter(name_direct_loantaker == "Nanaimo Forest Products Ltd.")

match_name(nanaimo_lbk, ald_demo) %>% 
  select(
    score, 
    starts_with("simpler_"), 
    name_direct_loantaker_lbk,
    name_ultimate_parent_lbk
  )
#> # A tibble: 2 x 5
#>   score simpler_name_lbk  simpler_name_ald  name_direct_loant… name_ultimate_pa…
#>   <dbl> <chr>             <chr>             <chr>              <chr>            
#> 1     1 abahydropowergen… abahydropowergen… <NA>               Aba Hydropower G…
#> 2     1 nanaimoforestpro… nanaimoforestpro… Nanaimo Forest Pr… <NA>
```

<sup>Created on 2019-12-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
