### ISSUE TITLE
Review Home and Get Started

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.match#71]
We now have wrappers that I believe complete the entire matching process. This boils down to [`match_name()`](https://2degreesinvesting.github.io/r2dii.match/reference/match_name.html) and [`prioritize()`](https://2degreesinvesting.github.io/r2dii.match/reference/prioritize.html), plus some helpers (see [all functions](https://2degreesinvesting.github.io/r2dii.match/reference/index.html)).

I updated the [Home page](https://2degreesinvesting.github.io/r2dii.match/index.html) of the package (README).

* @2diiKlaus and @jdhoffa, this is now ready for another pass of your feedback. 
* @jdhoffa, you may want to re-read/edit the [Get Started](https://2degreesinvesting.github.io/r2dii.match/articles/r2dii.match.html) section you wrote a while ago.

**Comment by 2diiKlaus** [comment]
To my knowledge @jdhoffa is reviewing it. Please let me know if my review is needed on top of this. Otherwise I won't act on this for now. 

Make sure you let the bank team test it when going to banks from now onwards or are there any reasons why that shouldn't be done @jdhoffa ?

**Comment by jdhoffa** [comment]
I think the code should be tested at banks definitely! There may be a bit of legwork required to massage the dataframes to look the same (reshaping and renaming columns on the input and output of the matching, but other than that it should be useable. 

Working on the ReadMe and Get Started now

**Comment by maurolepore** [comment]
@jdhoffa, after #97 I think you should focus on README.md only.

**Comment by jdhoffa** [comment]
copy that

**Comment by maurolepore** [comment]
Passing by I see this open but I think there is nothing else to do here. Other than directing our "alpha users" to readme and collect their feedback.

BTW, @jdhoffa, should we ask Florence?
