### ISSUE TITLE
identify_loans_by_sector_and_level() needs to pivot on both id_ and name_ 

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.match#87]
As it stands, identify_loans_by_sector_and_level() pivots only on `id_`, leaving redundant columns with prefix `name_`

**Comment by jdhoffa** [comment]
relates to `identify_loans_by_name_and_source()`. Combine these two functions, and remove hardcoding of `direct_loantaker` and `ultimate_parent`

**Comment by maurolepore** [comment]
@jdhoffa, I suspect this was done via #94. These two functions are called on data, and one after the other. I think the job is done, except that I don't see how `identify_loans_by_sector_and_level()` does anything to `sector`. Maybe it's a left over from something this function used to do but no longer does? If so, we should rename to `identify_loans_by_level()`.

```r
identify_loans_by_sector_and_level <- function(data) {
  data %>%
    tidyr::pivot_longer(
      cols = tidyr::starts_with("id_"),
      names_to = "level",
      names_prefix = "id_",
      values_to = "id"
    )
}

identify_loans_by_name <- function(data) {
  data %>%
    tidyr::pivot_longer(
      cols = extract_level_names(data, prefix = "name_"),
      names_to = "level2",
      names_prefix = "name_",
      values_to = "name"
    ) %>%
    filter(.data$level == .data$level2) %>%
    mutate(level2 = NULL)
}
```

**Comment by jdhoffa** [comment]
yup we can take out sector. 
Initially this function included something to handle the `by_sector = TRUE` flag, but it seems this has been incorporated in a `left_join` later on.
