### ISSUE TITLE
Define columns output by match_name(), i.e. `id` and others

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.match#88]
Relates to https://github.com/2DegreesInvesting/r2dii.match/issues/27#issuecomment-572171866

> it is (or at least should be) the id at loan level
-- @jdhoffa 

I'd be nice to confirm with a test. It seems an important requirement. @jdhoffa, I'm assigning you following your comment that you might have some time to code. But I can take over.

**Comment by maurolepore** [comment]
Closing after @jdhoffa 's confirmation:  https://github.com/2DegreesInvesting/r2dii.match/issues/27#issuecomment-572180047

**Comment by jdhoffa** [comment]
@maurolepore i was wrong, just updated my comment. `id_lbk` is not at loan level, it is at _every_ level. `id_loan` should be at loan level

**Comment by maurolepore** [comment]
@jdhoffa, thanks for clarifying. This makes me think we should probably define explicitly the new columns that `match_name()` adds. Could you add to what I wrote under `# @return`? (https://2degreesinvesting.github.io/r2dii.match/reference/match_name.html#value)

And while you are there, Could you please review the entire help file of `match_name()`?

https://github.com/2DegreesInvesting/r2dii.match/blob/master/R/match_name.R

**Comment by jdhoffa** [comment]
Relates to #123 
Solved by #132
